In [41]:
import skimage.feature
import numpy as np
import time

In [46]:
image = np.random.randint(256, size = (256, 256))

In [47]:
image

array([[170,  90, 144, ...,  43,   9, 145],
       [232, 171, 199, ..., 158,  51,   7],
       [223,  83, 247, ..., 217,  32, 113],
       ..., 
       [ 39, 185,  61, ..., 210, 123,  94],
       [ 19, 139,  95, ...,  46, 213,  15],
       [ 95, 197, 229, ..., 197,   3, 174]])

In [48]:
#start time
start = time.time()

#make the value of each to 0~4
image = (image/50)
image.astype(int)

#calculate GLCM
result = skimage.feature.greycomatrix(image, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], levels = 256, symmetric = True)

#end time
end = time.time()

print(result)
print(str(end-start) + "ms")

[[[[4998 5114 5092 4936]]

  [[4833 4756 4911 4766]]

  [[5133 5078 5036 5120]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]]


 [[[4833 4756 4911 4766]]

  [[4804 4830 4802 4880]]

  [[4929 4838 4870 4884]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]]


 [[[5133 5078 5036 5120]]

  [[4929 4838 4870 4884]]

  [[4946 5120 5092 5000]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]]


 ..., 
 [[[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]]


 [[[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]]


 [[[   0    0    0    0]]

  [[   0    0    0    0]]

  [[   0    0    0    0]]

  ..., 
  [[   0    0    0    0]]

  [[   0    0    

(256, 256, 1, 4)

array([[2, 1, 5, ..., 1, 5, 3],
       [5, 1, 1, ..., 3, 3, 1],
       [5, 2, 5, ..., 2, 1, 4],
       ..., 
       [2, 1, 5, ..., 1, 3, 4],
       [5, 5, 4, ..., 1, 4, 5],
       [1, 2, 1, ..., 2, 1, 4]])

array([[119,  99, 172, ..., 161, 147,  16],
       [ 62, 217, 226, ..., 155, 120,  74],
       [119, 137, 192, ...,  67, 143,   3],
       ..., 
       [137,  10, 222, ...,   4, 121, 154],
       [ 44,  33, 101, ..., 210, 151,   8],
       [116,  30, 116, ..., 189, 117, 200]])