In [29]:
import skimage.feature
import numpy as np
import time

In [30]:
image = np.random.randint(256, size = (256, 256))

In [31]:
image

array([[231, 170, 193, ...,  61,  49, 202],
       [209, 225, 182, ...,  20,  80, 177],
       [137, 235, 145, ...,  70,   5,  35],
       ..., 
       [111,  53, 146, ..., 103,  25, 234],
       [223,  71, 251, ..., 236, 164,  86],
       [ 79,  18, 106, ...,  25, 230, 112]])

In [32]:
#start time
start = time.time()

#make the value of each to 0~4
image = (image/50)
image = image.astype(int)

#calculate GLCM
result = skimage.feature.greycomatrix(image, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], levels = 6, symmetric = True, normed = True)

#end time
end = time.time()

print(result)
print(str(end-start) + "ms")

[[[[ 0.03875613  0.03881584  0.03860294  0.03793925]]

  [[ 0.03838848  0.03770088  0.03839614  0.03758554]]

  [[ 0.03842678  0.03897732  0.03833487  0.03854671]]

  [[ 0.03781403  0.03775471  0.03746936  0.03789312]]

  [[ 0.03832721  0.03828527  0.03871783  0.03944637]]

  [[ 0.00445006  0.00459823  0.00461857  0.00472126]]]


 [[[ 0.03838848  0.03770088  0.03839614  0.03758554]]

  [[ 0.0372549   0.03850827  0.03667279  0.03738562]]

  [[ 0.03801317  0.03738562  0.03793658  0.03786236]]

  [[ 0.03690257  0.03676278  0.03772978  0.03823914]]

  [[ 0.03859528  0.0387697   0.03848805  0.03813918]]

  [[ 0.00459559  0.00472895  0.00458027  0.00465206]]]


 [[[ 0.03842678  0.03897732  0.03833487  0.03854671]]

  [[ 0.03801317  0.03738562  0.03793658  0.03786236]]

  [[ 0.03711703  0.03826221  0.03776042  0.03797001]]

  [[ 0.03763787  0.03742407  0.0370481   0.03677816]]

  [[ 0.03871017  0.03802384  0.03870251  0.03883891]]

  [[ 0.00476409  0.0046213   0.00487898  0.0046905 ]]]


 [[[

In [33]:
result.shape

(6, 6, 1, 4)

In [34]:
image.max()

5