In [69]:
import skimage.feature
import numpy as np
import time

In [70]:
image = np.random.randint(256, size = (256, 256))

In [71]:
image

array([[239,  90, 217, ...,  61,  40, 243],
       [ 61, 162,  99, ..., 107, 244, 169],
       [102, 211, 116, ..., 107, 186,  76],
       ..., 
       [206, 249,  67, ...,  32, 125, 179],
       [232, 180, 166, ..., 183, 157,  58],
       [135, 223, 110, ..., 221, 125, 164]])

In [72]:
image = image/256

In [73]:
#start time
start = time.time()

#make the value of each to 0~4
image = (image*8)
image = image.astype(int)

#calculate GLCM
result = skimage.feature.greycomatrix(image, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], levels = 8, symmetric = True, normed = True)

#end time
end = time.time()

print(result)
print(str(end-start) + "ms")

[[[[ 0.01551777  0.01557862  0.01643689  0.01547097]]

  [[ 0.01578585  0.01598616  0.0156633   0.01592464]]

  [[ 0.01542586  0.01554018  0.01529565  0.01541715]]

  [[ 0.01586244  0.01589389  0.01536458  0.0155248 ]]

  [[ 0.01567096  0.01553249  0.01604626  0.01536332]]

  [[ 0.01565564  0.01519416  0.01544884  0.01555556]]

  [[ 0.01576287  0.0160323   0.01554075  0.01619377]]

  [[ 0.01593137  0.01581699  0.01576287  0.01612457]]]


 [[[ 0.01578585  0.01598616  0.0156633   0.01592464]]

  [[ 0.01470588  0.01560938  0.0157935   0.01557862]]

  [[ 0.01567096  0.01575548  0.01574755  0.01557862]]

  [[ 0.01582414  0.01594771  0.01571691  0.01534025]]

  [[ 0.01599265  0.01583237  0.01551777  0.01554018]]

  [[ 0.01587776  0.01540177  0.0151348   0.01557093]]

  [[ 0.01606158  0.01636294  0.0167739   0.01639369]]

  [[ 0.01623775  0.01527874  0.01581648  0.0162476 ]]]


 [[[ 0.01542586  0.01554018  0.01529565  0.01541715]]

  [[ 0.01567096  0.01575548  0.01574755  0.01557862]]

  [[ 0

In [57]:
result.shape

(8, 8, 1, 4)

In [58]:
image.max()

7