In [1]:
import keras.backend as K
import numpy as np

Using TensorFlow backend.


In [2]:
image = np.random.randint(0, 255, size = (256, 256))
image_keras_variable = K.variable(image)

In [3]:
image.shape

(256, 256)

In [4]:
K.eval(image_keras_variable)

array([[  32.,  153.,   69., ...,  106.,  229.,   63.],
       [ 198.,    4.,  238., ...,  142.,  170.,  193.],
       [ 157.,  253.,   52., ...,    5.,   75.,   76.],
       ..., 
       [ 148.,  157.,   95., ...,  126.,  191.,    5.],
       [ 116.,  232.,   42., ...,   80.,  242.,  158.],
       [ 175.,   80.,   90., ...,   61.,  153.,  107.]], dtype=float32)

In [5]:
def binarization(x):
    bi_x = K.sign(x)
    return bi_x

In [6]:
image_bi = binarization(image_keras_variable)

In [7]:
K.eval(image_bi)

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]], dtype=float32)

In [8]:
K.shape(image_keras_variable).eval(session=K.get_session())

array([256, 256], dtype=int32)

In [9]:
output = K.placeholder(shape = (2, 2))

In [11]:
import tensorflow as tf

def GLCM_bi(image):
    output = K.placeholder(shape = (2, 2))
    for i in range(0, 255):
        for j in range(0, 254):
            K.eval(tf.subtract(tf.add(image[i][j], image[i][j+1]), tf.multiply(image[i][j], image[i][j+1])))
            
    

In [ ]:
#執行這步跑上面函式會死掉
GLCM_bi(image_bi)

In [35]:
output = K.zeros(shape = (2, 2))
a = tf.add(image_bi[0][0], image_bi[1][1])


In [39]:
a

<tf.Tensor 'Add_12:0' shape=() dtype=float32>

In [41]:
output[0][0]

<tf.Tensor 'strided_slice_75:0' shape=() dtype=float32>

In [38]:
K.update_add(output[0][0], a)

TypeError: Input 'ref' of 'AssignAdd' Op requires l-value input

In [33]:
type(output[0][0])

tensorflow.python.framework.ops.Tensor

In [34]:
type(output)

tensorflow.python.framework.ops.Tensor

In [ ]:
a